#Notification-Service Server Details
server:
 port: 9393
 
#Notification-Service Producer Details
spring:
 kafka:
  producer:
   bootstrap-servers: localhost:9092
   key-serializer: org.apache.kafka.common.serialization.StringSerializer
   value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#Notification-Service Consumer Details
  consumer:
   bootstrap-servers: localhost:9092
   group-id: payment-consumer
   key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
   value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
   properties:
    spring:
     json:
      trusted:
       packages: "*"